### ISSUE TITLE
已搭建好青龙怎么用呢？

### ISSUE THREAD

**Issue by kwf2030** [ShuaiLeiLu/JD_Scripts#1]
青龙面板已搭建好，新建任务时命令应该怎么填呢。
是这样吗？ql repo https://github.com/ShuaiLeiLu/JD.git，后面该怎么写啊

**Comment by ShuaiLeiLu** [comment]
这是helloword的适配库，青龙不一定适配的！你自己找一下青龙的适配库

**Comment by ShuaiLeiLu** [comment]
> 青龙面板已搭建好，新建任务时命令应该怎么填呢。 是这样吗？ql repo [https://github.com/ShuaiLeiLu/JD.git，后面该怎么写啊](https://github.com/ShuaiLeiLu/JD.git%EF%BC%8C%E5%90%8E%E9%9D%A2%E8%AF%A5%E6%80%8E%E4%B9%88%E5%86%99%E5%95%8A)
ql repo https://github.com/ShuaiLeiLu/JD.git "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR"   你可以拉一下试试看

**Comment by ShuaiLeiLu** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
