### ISSUE TITLE
清空购物车两个脚本怎么用

### ISSUE THREAD

**Issue by Ginua8292** [ShuaiLeiLu/JD_Scripts#2]
jd_cleancart         清空购物车, 失败! 原因: TypeError: cartData is not iterable!

jd_cleancart_nolan.js
❗️清空购物车-Sign版, 错误!
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/scripts/ShuaiLeiLu_JD/jd_cleancart_nolan.js:299:29
    at /ql/scripts/ShuaiLeiLu_JD/jd_cleancart_nolan.js:359:5858
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
获取不到算法

两个都用不了!

**Comment by ShuaiLeiLu** [comment]
你是库没拉全吗，我这两个都可以使用哦
