### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by xinxinwuwu** [ShuaiLeiLu/JD_Scripts#4]
10.12日左右 代挂的部分功能（包括京豆、农场、种豆得豆、试用等）失效，只有签到的奖励。
10.15 再次登录主链接，后面几天并没有明显改善
10.17-10.18 代挂京豆数量有明显改善，但是农场攒水滴、试用等模块依然是没在启用状态。
请问是黑号了还是其他情况

**Comment by ShuaiLeiLu** [comment]
农场没黑号的基本已经修复
种豆得豆脚本已经修复
试用脚本跑一个账号时间太长，如果并发跑账号太容易黑了，所以设置默认只开启了前十个账号，如果需要试用建议自己搭建一个
最后感谢反馈
