### ISSUE TITLE
代挂的网站源码有开源吗？

### ISSUE THREAD

**Issue by jeck5001** [ShuaiLeiLu/JD_Scripts#7]
![image](https://user-images.githubusercontent.com/8085554/216270911-64b4dd07-e029-4bc2-b0a9-e455f75631d5.png)
你好，我想用代挂的网站里方式的获取京东cookie，有开源吗？

**Comment by ShuaiLeiLu** [comment]
登录用的是nark和BBK

**Comment by jeck5001** [comment]
> 登录用的是nark和BBK

nark没有授权码用不了啊，话说BBK是啥？
